"""add game ids to user

Revision ID: 17bba9741c78
Revises: 5d65eba2953a
Create Date: 2026-03-11 12:45:13.517662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17bba9741c78'
down_revision: Union[str, Sequence[str], None] = '5d65eba2953a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bgmi_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('valorant_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('freefire_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'freefire_id')
    op.drop_column('users', 'valorant_id')
    op.drop_column('users', 'bgmi_id')
    # ### end Alembic commands ###
