"""Add game_image_url to tournaments

Revision ID: 5d65eba2953a
Revises: 838077eb6c42
Create Date: 2026-03-11 10:43:27.085826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d65eba2953a'
down_revision: Union[str, Sequence[str], None] = '838077eb6c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('game_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'game_image_url')
    # ### end Alembic commands ###
