"""Add performance indexes

Revision ID: 8010dcb382ed
Revises: db910f5991e5
Create Date: 2026-04-13 10:47:25.182200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8010dcb382ed'
down_revision: Union[str, Sequence[str], None] = 'db910f5991e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_media_expires_at'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_is_read'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_timestamp'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_user_created_at'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.alter_column('tournament_participants', 'team_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tournament_participants', 'team_join_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_tp_team_join_code'), table_name='tournament_participants', postgresql_where='(team_join_code IS NOT NULL)')
    op.drop_index(op.f('uq_tournament_participant_slot_idx'), table_name='tournament_participants', postgresql_where='(slot_no IS NOT NULL)')
    op.create_index(op.f('ix_tournament_participants_team_join_code'), 'tournament_participants', ['team_join_code'], unique=False)
    op.drop_index(op.f('ix_tournaments_status_match_time'), table_name='tournaments')
    op.create_index(op.f('ix_tournaments_created_at'), 'tournaments', ['created_at'], unique=False)
    op.create_index(op.f('ix_tournaments_match_time'), 'tournaments', ['match_time'], unique=False)
    op.create_index(op.f('ix_tournaments_status'), 'tournaments', ['status'], unique=False)
    op.alter_column('users', 'deposit_balance',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('users', 'winning_balance',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('users', 'bonus_balance',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('users', 'daily_spin_limit',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'daily_spin_used',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.drop_index(op.f('ix_wallet_tx_created_at'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_tx_type_status_created_at'), table_name='wallet_transactions')
    op.create_index(op.f('ix_wallet_transactions_created_at'), 'wallet_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_status'), 'wallet_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_transaction_type'), 'wallet_transactions', ['transaction_type'], unique=False)
    op.create_index('ix_wallet_transactions_type_status_created', 'wallet_transactions', ['transaction_type', 'status', 'created_at'], unique=False)
    op.create_index('ix_wallet_transactions_user_created', 'wallet_transactions', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wallet_transactions_user_created', table_name='wallet_transactions')
    op.drop_index('ix_wallet_transactions_type_status_created', table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_transaction_type'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_status'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_created_at'), table_name='wallet_transactions')
    op.create_index(op.f('ix_wallet_tx_type_status_created_at'), 'wallet_transactions', ['transaction_type', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_wallet_tx_created_at'), 'wallet_transactions', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.alter_column('users', 'daily_spin_used',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'daily_spin_limit',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'bonus_balance',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('users', 'winning_balance',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('users', 'deposit_balance',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.drop_index(op.f('ix_tournaments_status'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_match_time'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_created_at'), table_name='tournaments')
    op.create_index(op.f('ix_tournaments_status_match_time'), 'tournaments', ['status', 'match_time'], unique=False)
    op.drop_index(op.f('ix_tournament_participants_team_join_code'), table_name='tournament_participants')
    op.create_index(op.f('uq_tournament_participant_slot_idx'), 'tournament_participants', ['tournament_id', 'slot_no'], unique=True, postgresql_where='(slot_no IS NOT NULL)')
    op.create_index(op.f('ix_tp_team_join_code'), 'tournament_participants', ['team_join_code'], unique=False, postgresql_where='(team_join_code IS NOT NULL)')
    op.alter_column('tournament_participants', 'team_join_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tournament_participants', 'team_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('attended_by_admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('attended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('requires_admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('blocked_by_admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('blocked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('issue_type', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('issue_ack_sent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_user_blocked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('ended_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ended_by_role', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['attended_by_admin_id'], ['users.id'], name=op.f('chat_sessions_attended_by_admin_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('chat_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_sessions_pkey'))
    )
    op.create_index(op.f('ix_chat_sessions_user_created_at'), 'chat_sessions', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('media_type', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('media_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('media_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('media_mime_type', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('media_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('media_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint('length(content) <= 1000', name=op.f('ck_chat_messages_content_len')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('chat_messages_sender_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('chat_messages_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_messages_pkey'))
    )
    op.create_index(op.f('ix_chat_messages_session_timestamp'), 'chat_messages', ['session_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_is_read'), 'chat_messages', ['session_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_chat_messages_media_expires_at'), 'chat_messages', ['media_expires_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    # ### end Alembic commands ###
