"""add_rps_tables

Revision ID: a78dca0e3ffb
Revises: zzzzzzzzzzzz
Create Date: 2026-07-10 15:33:08.395033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a78dca0e3ffb'
down_revision: Union[str, Sequence[str], None] = 'zzzzzzzzzzzz'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rps_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('prize_pool', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rps_matches_id'), 'rps_matches', ['id'], unique=False)
    op.create_index(op.f('ix_rps_matches_status'), 'rps_matches', ['status'], unique=False)
    op.create_table('rps_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('move', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['rps_matches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rps_participants_id'), 'rps_participants', ['id'], unique=False)
    op.drop_index(op.f('ix_chat_messages_session_is_read'), table_name='chat_messages')
    op.add_column('chat_sessions', sa.Column('is_pinned', sa.Boolean(), nullable=False))
    op.alter_column('chat_sessions', 'issue_ack_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('chat_sessions', 'is_user_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_chat_sessions_user_created_at'), table_name='chat_sessions')
    op.create_index(op.f('ix_chat_sessions_status'), 'chat_sessions', ['status'], unique=False)
    op.create_foreign_key(None, 'chat_sessions', 'users', ['ended_by_user_id'], ['id'])
    op.create_foreign_key(None, 'chat_sessions', 'users', ['blocked_by_admin_id'], ['id'])
    op.alter_column('tournament_participants', 'kills',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('tournaments', 'entry_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('tournaments', 'prize_pool',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('tournaments', 'commission_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('tournaments', 'prize_distribution',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('users', 'wallet_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('users', 'token_version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'daily_bonus_used',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('users', 'xp',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'level',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'mmr',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1200'))
    op.drop_constraint(op.f('users_referral_code_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_foreign_key(None, 'users', 'users', ['referred_by_id'], ['id'])
    op.drop_column('users', 'hashed_password')
    op.alter_column('wallet_transactions', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('wallet_transactions', 'remark',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_wallet_tx_created_at'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_tx_type_status_created_at'), table_name='wallet_transactions')
    op.create_index(op.f('ix_wallet_transactions_gateway_order_id'), 'wallet_transactions', ['gateway_order_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_gateway_payment_id'), 'wallet_transactions', ['gateway_payment_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_payu_txn_id'), 'wallet_transactions', ['payu_txn_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_transactions_payu_txn_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_gateway_payment_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_gateway_order_id'), table_name='wallet_transactions')
    op.create_index(op.f('ix_wallet_tx_type_status_created_at'), 'wallet_transactions', ['transaction_type', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_wallet_tx_created_at'), 'wallet_transactions', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('wallet_transactions', 'remark',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('wallet_transactions', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_unique_constraint(op.f('users_referral_code_key'), 'users', ['referral_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'mmr',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1200'))
    op.alter_column('users', 'level',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'xp',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'daily_bonus_used',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('users', 'token_version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'wallet_balance',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('tournaments', 'prize_distribution',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('tournaments', 'commission_percentage',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('tournaments', 'prize_pool',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('tournaments', 'entry_fee',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('tournament_participants', 'kills',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_chat_sessions_status'), table_name='chat_sessions')
    op.create_index(op.f('ix_chat_sessions_user_created_at'), 'chat_sessions', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('chat_sessions', 'is_user_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('chat_sessions', 'issue_ack_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('chat_sessions', 'is_pinned')
    op.create_index(op.f('ix_chat_messages_session_is_read'), 'chat_messages', ['session_id', 'is_read'], unique=False)
    op.drop_index(op.f('ix_rps_participants_id'), table_name='rps_participants')
    op.drop_table('rps_participants')
    op.drop_index(op.f('ix_rps_matches_status'), table_name='rps_matches')
    op.drop_index(op.f('ix_rps_matches_id'), table_name='rps_matches')
    op.drop_table('rps_matches')
    # ### end Alembic commands ###
