"""Add persistent thread support to chat

Revision ID: eeccdc942bc2
Revises: 56ace62cf209
Create Date: 2026-04-13 15:50:05.414151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeccdc942bc2'
down_revision: Union[str, Sequence[str], None] = '56ace62cf209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('thread_user_id', sa.Integer(), nullable=True))
    op.add_column('chat_messages', sa.Column('read_at', sa.DateTime(), nullable=True))
    op.add_column('chat_messages', sa.Column('is_delivered', sa.Boolean(), nullable=True))
    op.add_column('chat_messages', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_chat_messages_session_is_read'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_timestamp'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_unread'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_sender_id'), 'chat_messages', ['sender_id'], unique=False)
    op.create_index('ix_chat_messages_status', 'chat_messages', ['thread_user_id', 'is_admin', 'is_read', 'is_delivered'], unique=False)
    op.create_index('ix_chat_messages_thread_timestamp', 'chat_messages', ['thread_user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_chat_messages_thread_user_id'), 'chat_messages', ['thread_user_id'], unique=False)
    op.create_foreign_key(None, 'chat_messages', 'users', ['thread_user_id'], ['id'])
    op.drop_index(op.f('ix_chat_sessions_user_created_at'), table_name='chat_sessions')
    op.drop_index(op.f('ix_wallet_tx_created_at'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_tx_type_status_created_at'), table_name='wallet_transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_wallet_tx_type_status_created_at'), 'wallet_transactions', ['transaction_type', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_wallet_tx_created_at'), 'wallet_transactions', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_created_at'), 'chat_sessions', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_index(op.f('ix_chat_messages_thread_user_id'), table_name='chat_messages')
    op.drop_index('ix_chat_messages_thread_timestamp', table_name='chat_messages')
    op.drop_index('ix_chat_messages_status', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_sender_id'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_unread'), 'chat_messages', ['session_id', 'is_admin', 'is_read'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_timestamp'), 'chat_messages', ['session_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_is_read'), 'chat_messages', ['session_id', 'is_read'], unique=False)
    op.drop_column('chat_messages', 'delivered_at')
    op.drop_column('chat_messages', 'is_delivered')
    op.drop_column('chat_messages', 'read_at')
    op.drop_column('chat_messages', 'thread_user_id')
    # ### end Alembic commands ###
